# Generated by Django 6.0.5 on 2026-05-23 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Medical', 'Medical'), ('Homeless', 'Homeless'), ('Education', 'Education'), ('Food', 'Food')], max_length=50)),
                ('description', models.TextField()),
                ('goal', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='donation',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='api.cause'),
        ),
    ]
